#include<stdio.h>
#include<string.h>
#include<ctype.h>
#include"structure.h"

void voter_func(){
    int flip;
    printf("*******************************************\n");
    printf("press 1 to register\n");
    printf("press 2 fo login\n");
    printf("press 3 to view election schedule\n");
    printf("press 4 to view election result\n");
    printf("press 5 for main menu\n");
    printf("*******************************************\n");
    printf("Enter your choice");
    scanf("%d",&flip);
    switch(flip){
        case 1:
            add_user();
            break;
        case 2:
            login_user();
            break;
        case 3:
            election_schedule();
            break;
        case 4:
            election_res();
            break;
        case 5:
            main();
            break;
        default:
            printf("Invalid Input\n");
            voter_func();
            return;
    }   
}
void add_user(){
    user_struct user;
    char d_o_b[20];
    char valid_date[20];
    char mobile[20];
    char valid_mobile[20];
    int u_age;
    int valid_u_age=0;
    char gender_valid[20];
    char valid_gender[20];

    strcpy(user.status , "disapproved");
    /////// USER ID AUTO GENERATION
    //printf("Enter id");
    
    scanf("%s",user.u_id);



    printf("Enter first name of User");
    scanf("%s",user.first_name);
    printf("Enter last name of User");
    scanf("%s",user.last_name);
    
    /// Date Validation//////////////////////////////////
    printf("Enter DOB");
    scanf("%s",d_o_b);
    date_valid(d_o_b,valid_date);
    strcpy(user.dob,valid_date);

    // age validation/////////////////////////////////////
    printf("Enter age");
    scanf("%d",&u_age);
    age_valid(u_age, valid_u_age);    
    user.age = valid_u_age;

    // gender validate/////////////////////////////////
    printf("Enter Gender");
    scanf("%s",gender_valid);
    gender_validate(gender_valid,valid_gender);
    strcpy(user.gender,valid_gender);


    printf("Enter password");
    scanf("%s",user.password);
    printf("Enter address");
    scanf("%s",user.address);
    
    // mobile validation///////////////////////////////
    printf("Enter phone no.");
    scanf("%s",mobile);
    mobile_validation(mobile,valid_mobile);
    strcpy(user.phoneno,valid_mobile);

    printf("Enter district");
    scanf("%s",user.district);
    
    clearInputBuffer();
    printf("Enter constituency");
    fgets(user.consituency, sizeof(user.consituency), stdin);

 
    FILE *file = fopen("user.csv","a");
    if(file==NULL){
        printf("Error opening file");
        return;
    }



    fprintf(file, "%s,%s,%s,%s,%s,%d,%s,%s,%s,%s,%s,%s",
    user.status,user.u_id,user.first_name,user.last_name,user.dob,user.age,user.gender,user.password,
    user.address,user.phoneno,user.district,user.consituency);

    fclose(file);

    printf("Candidate details added successfully to user.csv.\n");

}

void login_user(){
    char user_id[100];
    char pass[100];
    user_struct user;
    
    printf("Enter your user id");
    scanf("%s",user_id);
    printf("Enter your passwrd");
    scanf("%s",pass);
    
    FILE *file = fopen("user.csv","r");
    
    int count=0;
    
    while (fscanf(file, "%[^,],%[^,],%[^,],%[^,],%[^,],%d,%[^,],%[^,],%[^,],%[^,],%[^,],%[^\n]\n",
                  user.status, user.u_id, user.first_name, user.last_name, user.dob, &user.age,
                  user.gender, user.password, user.address, user.phoneno, user.district,
                  user.consituency) == 12) {
            printf("%s$$$$$$$$$$$\n",user.u_id);
            printf("%s$$$$$$$$$$$\n",user.password);

            if((strcmp(user.u_id,user_id)==0) && (strcmp(user.password,pass)==0)){
                printf("login successful");
                voter_dash(user_id);
                count=1;
                break;
            }
        }
        if(count==0){
            printf("User not found please please enter correct user id\n ");
            login_user();
        }
    fclose(file);
}
void voter_dash(char user_id[100]){
    int flip;
    printf("\n*******************************************\n");
    printf("press 1 to send voter id request\n");
    printf("press 2 to view voter id generated by eletoral officer\n");
    printf("press 3 to cast vote\n");
    printf("press 4 for logout\n");
    printf("*******************************************\n");
    printf("Enter your choice ");
    scanf("%d",&flip);

    switch(flip){
        case 1:
            req_to_approval(user_id);
            break;
        case 2:
            view_voter_id(user_id);
            break;
        case 3:
            show_candi(user_id);
            break;
        case 4:
            voter_func();
            break;
        
        default:
            printf("please enter valid user id");
            voter_dash(user_id);
            return;
    }
}


void req_to_approval(char user_id[100]){
    user_struct user;
    FILE *file = fopen("user.csv","r");
    FILE *tmp = fopen("temp.csv","w");
    while (fscanf(file, "%[^,],%[^,],%[^,],%[^,],%[^,],%d,%[^,],%[^,],%[^,],%[^,],%[^,],%[^\n]\n",
                  user.status, user.u_id, user.first_name, user.last_name, user.dob, &user.age,
                  user.gender, user.password, user.address, user.phoneno, user.district,
                  user.consituency) == 12) {
            if(strcmp(user_id,user.u_id)==0){
                strcpy(user.status, "req_to_approval");
            }
            fprintf(tmp, "%s,%s,%s,%s,%s,%d,%s,%s,%s,%s,%s,%s\n",
                    user.status,user.u_id,user.first_name,user.last_name,user.dob,user.age,user.gender,user.password,
                    user.address,user.phoneno,user.district,user.consituency);   
    }
    fclose(file);
    fclose(tmp);

    remove("user.csv");
    rename("temp.csv","user.csv");
}

void view_voter_id(char user_id[100]){
    user_struct user;
    FILE *file = fopen("user.csv","r");
     while (fscanf(file, "%[^,],%[^,],%[^,],%[^,],%[^,],%d,%[^,],%[^,],%[^,],%[^,],%[^,],%[^\n]\n",
                  user.status, user.u_id, user.first_name, user.last_name, user.dob, &user.age,
                  user.gender, user.password, user.address, user.phoneno, user.district,
                  user.consituency) == 12) {

                    if(strcmp(user.u_id,user_id)==0){
                        printf("Your voter id is %s",user.status);
                        
                    }
    }
}

void show_candi(char user_id[100]){
    candidate cad;
    user_struct user;
    char voterid[20];
    char consti[100];
    char userid[20];
    FILE *u_file = fopen("user.csv","r");
    FILE *c_file = fopen("candidate.csv","r");
    //FILE *tmp = fopen("temp.csv","w");
    //printf("~~~~~~~~~~~~~~~~~~~HI~~~~~~~~~~~~~~~~\n");
    //char u_line[1000];
    while (fscanf(u_file, "%[^,],%[^,],%[^,],%[^,],%[^,],%d,%[^,],%[^,],%[^,],%[^,],%[^,],%[^\n]\n",
                  user.status, user.u_id, user.first_name, user.last_name, user.dob, &user.age,
                  user.gender, user.password, user.address, user.phoneno, user.district,
                  user.consituency) == 12) {
         if(strcmp(user.u_id,user_id)==0){
            strcpy(consti, user.consituency);
            strcpy(voterid,user.status);
            strcpy(userid,user.u_id);
         }
    }
////////////////////////////////////////////////////////////////    
    if((strcmp(voterid,"disapproved")==0)){
        printf("Your have not not requested to generate voter id is not generated hence you cant vote\n");
        voter_dash(userid);
    }
    else if((strcmp(voterid,"req_to_approval")==0) || (strcmp(voterid,"approved")==0)){
        printf("your voter not been approved or not generated\n");
        main();
    }
    else{    
        char c_line[1000];
        while(fgets(c_line,sizeof(c_line),c_file)!=NULL){
            sscanf(c_line,"%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,]",
            cad.candidate_id,cad.candidate_name,cad.dob,cad.election_name,cad.party_name,cad.district,cad.constituency,cad.address,
            cad.phone_no,cad.email_id,cad.vote_count);
                    
            if(strcmp(cad.constituency,consti)==0){
                printf("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",cad.candidate_id,cad.candidate_name,cad.dob,cad.election_name,cad.party_name,cad.district,cad.constituency,cad.address,
                cad.phone_no,cad.email_id);
                }
            }
            cast_vote();
    }
}


void cast_vote(){
    candidate cad;
    FILE *c_file = fopen("candidate.csv","r");
    FILE *tmp = fopen("temp.csv","w");
    char vote[100];
        printf("\nEnter candidate id to yoy want to give vote\n");
        scanf("%s",vote);

        char cline[1000];
        while(fgets(cline,sizeof(cline),c_file)!=NULL){
            printf("*");
            sscanf(cline,"%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,]",
            cad.candidate_id,cad.candidate_name,cad.dob,cad.election_name,cad.party_name,cad.district,cad.constituency,cad.address,
            cad.phone_no,cad.email_id,cad.vote_count);

            if(strcmp(cad.candidate_id,vote)==0){
                cad.vote_count[0]=cad.vote_count[0]+1;
                // printf("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s",cad.candidate_id,cad.candidate_name,cad.dob,cad.election_name,cad.party_name,cad.district,cad.constituency,cad.address,
                //     cad.phone_no,cad.email_id,cad.vote_count);
            }

            fprintf(tmp,"%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s",cad.candidate_id,cad.candidate_name,cad.dob,cad.election_name,cad.party_name,cad.district,cad.constituency,cad.address,
            cad.phone_no,cad.email_id,cad.vote_count);
        }

        fclose(c_file);
        fclose(tmp);

        remove("candidate.csv");
        rename("temp.csv","candidate.csv");

        printf("\nYour vote has been recored successfully");
}


void election_res(){
    candidate cad;
    char consti[50];
    //if(strlen(user))
    printf("enter constiuency you want to view result");
    //scanf("%[^\n]",consti);
    scanf(" %[^\n]", consti);
    printf("%s",consti);
    FILE *file = fopen("candidate.csv","r");

    char line[1000];
    while(fgets(line,sizeof(line),file)){
        sscanf(line,"%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,],%[^,]",cad.candidate_id,cad.candidate_name,cad.dob,cad.election_name,cad.party_name,cad.district,cad.constituency,cad.address,
        cad.phone_no,cad.email_id,cad.vote_count);
        //printf("_________%s  %s____________\n",cad.constituency,consti);
        if(strcmp(cad.constituency,consti)==0){
            printf("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",cad.candidate_id,cad.candidate_name,cad.dob,cad.election_name,cad.party_name,cad.district,cad.constituency,cad.address,
                cad.phone_no,cad.email_id,cad.vote_count);
        }
    }
}

void clearInputBuffer() {
    int c;
    while ((c = getchar()) != '\n' && c != EOF) {}
}